spring:
  thymeleaf:
    cache: false

server:
  servlet:
    session:
      tracking-modes: cookie

eureka:
  client:
    registerWithEureka: false

service:
  web:
    service-urls:
      location-service: http://localhost:8082/location/