server:
  # Port for Config Server
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          # URL of the Git Repository
          uri:  https://github.com/ryanjbaxter/beginners-guide-to-spring-cloud
          # Subdirectories of the repository (if any)
          searchPaths: beginners-guide-to-spring-cloud-config
          # Branch name
          default-label: master
          #username: Git username (if required)
          #password: Git password Or Personal Access Token (if required)

eureka:
  client:
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost