spring:
  application:
    name: location-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: false

#logging:
#  level:
#    root: debug

#eureka:
#  client:
#    registerWithEureka: false

#service:
#  location:
#    cities:
#      - id: 1
#        name: London
#        query: London,uk
#      - id: 2
#        name: Paris
#        query: Paris,fr