spring:
  application:
    name: location-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: false